### ISSUE TITLE
grids around the component make it render above, not below

### ISSUE THREAD

**Issue by mgenev** [soulim/ember-cli-bootstrap-datepicker#22]
When I have this component in a  grid, it renders above its current position and spills out of bounds.

**Comment by soulim** [comment]
Could you provide an example with JSBin or repo? That would help a lot with reproduction of the issue.

**Comment by mgenev** [comment]
Ok, I'll try soon.

**Comment by soulim** [comment]
@mgenev do you have any updates on this issue? Actually I'm really not sure that the add-on causes this problem for you, because the add-on provides just input field. The problem might be somewhere in your custom CSS.

You could take a look at [demo page][1]. It uses Bootstrap CSS and the add-on, and everything seems fine.

[1]: http://sul.im/ember-cli-bootstrap-datepicker/
