### ISSUE TITLE
Add support for picking time as well?

### ISSUE THREAD

**Issue by nesevis** [soulim/ember-cli-bootstrap-datepicker#40]
Great work so far!

A couple of suggested improvements:
- the ability to pick times (timePicker: true; timePickerIncrement: x)
- the ability to select an output format. It handles being given an ISO8601 input (Ember standard), but outputs a JS standard date.

**Comment by jelhan** [comment]
Are you sure an ISO 8601 string as input is working? As far as I have tested and unterstood the code everything else than a Date object is not supported as input. https://github.com/soulim/ember-cli-bootstrap-datepicker/blob/master/addon/components/datepicker-support.js#L110-119 tests the type of input. If it's not a Date object or an array (multiple option) value is set to `null`. If you use multiple option and use anything else than a Date object you run in a TypeError because method `setHours` does not exist.

If you need to convert the Date object to another format you should use a computed property as value.

If you need to select dates with specified times you should consider using [ember-bootstrap-datetimepicker](ember-cli-bootstrap-datetimepicker).

**Comment by soulim** [comment]
@nesevis there'are no plans for time picking feature. Strictly speaking this component is just a wrapper around awesome [bootstrap-datepicker library][1]. So time picking might be available when someone adds it to the bootstrap-datepicker.

@jelhan is right - if you need time picking functionality it's better to play with [ember-bootstrap-datetimepicker][2].

And again @jelhan is totally correct. The component uses Javascript native Date objects, not ISO8601 strings.

Thank you @jelhan for help and support! :heart: 

[1]: https://github.com/eternicode/bootstrap-datepicker
[2]: https://github.com/soulim/ember-cli-bootstrap-datepicker/issues/ember-cli-bootstrap-datetimepicker

**Comment by soulim** [comment]
I close this issue because time picking functionality doesn't belong to the component itself.
